doors:
  build: ./doors
  volumes:
    - "./data/doors/home/:/var/doors/.doors/"
  links:
    - mail:mail
  ports:
    - 8989:8989
mail:
  build: ./mail
  environment:
    - HOST=doors.iscpif.fr
  volumes:
    - "./data/mail/spool:/var/spool/postfix"
https-portal:
  image: steveltn/https-portal
  ports:
    - 80:80
    - 443:443
  links:
    - doors
  environment:
    - "DOMAINS=localhost -> http://doors"
    #- "CLIENT_MAX_BODY_SIZE=4G" 
    #- "PRODUCTION=true"     


